[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "{{cookiecutter.package_name}}"
version = "0.1.0"
requires-python = ">={{cookiecutter.python_version}}"
dependencies = []
authors = [
  {name = "{{cookiecutter.author_name}}", email = "{{cookiecutter.author_email}}"}
]
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.optional-dependencies]
lint = [
    "ruff",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # Pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "UP",  # pyupgrade
]

[project.scripts]
entrypoint = "{{cookiecutter.package_name}}.component:function"
